### ISSUE TITLE
Scorch marks not removed

### ISSUE THREAD

**Issue by vavavr00m** [Sil3ntStorm/factorio-remove-nuclear-marks#1]
I believe this was either from artillery or atomic bomb.

![image](https://user-images.githubusercontent.com/4675132/226610048-59905fb8-2885-45f5-a6cf-a43d48c8927f.png)

**Comment by Sil3ntStorm** [comment]
Can you provide the save game, or alternatively in what way these were created (ie. what did you do to make them appear)?

**Comment by Sil3ntStorm** [comment]
You did not research atomic weaponry and thus it shouldn't be possible for you to be producing nuclear marks like that. I guess one of the other mods installed will allow you to create nuclear explosions without having access to the weaponry.
It's a lockout from when the tool was exclusively doing Nuclear stuff and was only available after nuclear weapons have been unlocked.

**Comment by vavavr00m** [comment]
I requested for a player, who has already researched nuclear stuff, to clear that area. I also spawned an atomic bomb to confirm it was what was also causing the nuclear marks apart from the artillery weapon because he wasn't around when you asked. Are you able to fix the tool?
