### ISSUE TITLE
Recover the original map tile

### ISSUE THREAD

**Issue by morsk** [Sil3ntStorm/factorio-remove-nuclear-marks#2]
I will add it if you approve it, as I recently wrote something similar for fixing 1.1 landfill tiles. You can recover the original tile by creating a 2nd surface and checking its tiles from map generation.

This is especially useful if someone nukes landfill, and then can't remove the landfill. They end up with nuclear ground in the middle of a lake, and the mod only succeeds in turning it to dirt, not water.

**Comment by Sil3ntStorm** [comment]
Interesting idea. I thought each surface had their own, but yeah you can actually get the same, which I never noticed before. I'd be down for that.
If you want you can take a stab at it, otherwise I can do it as well.

**Comment by morsk** [comment]
It's here: https://github.com/Sil3ntStorm/factorio-remove-nuclear-marks/commit/3813b2c441b9e37e62744f1a5ee8792f5d5a7d99

I can make a PR if you update the repository here to catch up with the mod portal, otherwise you could just copy things over.

It's possible that some users who've done weird things with map generation, and have seams in their maps, would prefer the old way. But for any normal map this is better, especially around water.
